package com.abo47.kubejslab.recipe.model;

public enum LabRecipeField {
    SHAPELESS,
    EXPERIENCE,
    COOKING_TIME,
    COUNT,
    PROCESSING_TIME,
    HEAT_REQUIREMENT,
    KEEP_HELD_ITEM,
    ACCEPT_MIRRORED,
    GRID_WIDTH,
    GRID_HEIGHT,
    OUTPUT_COUNT,
    ENERGY,
    CREOSOTE_AMOUNT,
    MOLD,
    BLUEPRINT_CATEGORY,
    CLOCHE_RENDER_TYPE,
    CLOCHE_RENDER_BLOCK
}
